/* Eco-Spine prototype: one source of truth for conceptual candidates and local observations. */
const ecoFrames = [
  { id: 'EF-001', status: 'proposed', locationName: 'Jurong Lake Gardens area — conceptual candidate', nearbyHabitat: 'Jurong Lake Gardens', role: 'Habitat node / connectivity support', maintenanceStatus: 'not installed' },
  { id: 'EF-002', status: 'proposed', locationName: 'Tengah Forest Corridor area — conceptual candidate', nearbyHabitat: 'Tengah Forest Corridor', role: 'Habitat node / connectivity support', maintenanceStatus: 'not installed' },
  { id: 'EF-003', status: 'proposed', locationName: 'Candidate to be selected on map', nearbyHabitat: 'TBC', role: 'To be assessed', maintenanceStatus: 'not installed' }
];
const plantList = [
  ['Simpoh Air (Dillenia suffruticosa)','Native','Nectar / shelter','High','Medium','Butterflies'],['Snakeweed (Stachytarpheta indica)','Non-native / verify for use','Nectar','High','Medium','Butterflies'],['Indian heliotrope (Heliotropium indicum)','Native status requires curation','Nectar','High','Low','Bees + butterflies'],['Golden penda (Xanthostemon chrysanthus)','Non-native','Pollen / nectar','High','Medium','Bees'],['Seven candles (Senna alata)','Non-native','Host / nectar potential','High','Medium','Butterflies'],['Blue pea (Clitoria ternatea)','Non-native','Nectar / host potential','High','Medium','Bees + butterflies'],['Shooting star (Pseuderanthemum reticulatum)','Non-native','Nectar','Medium','Medium','Butterflies'],['Beach sunflower (Melampodium divaricatum)','Non-native','Nectar','High','Low','Bees']
];
const parts = {cap:['01 / ANTI-BIRD FEATURES','45° sloped upper cap','A sloped upper cap and other features are proposed to discourage roosting or nesting, supporting site-specific operational constraints without harming birds.'],plant:['02 / PLANTING MODULES','Nectar, pollen, foliage + shelter','Planting modules are intended to provide floral resources, foliage and shelter for target pollinators. Plant selection would be site-specific.'],bee:['03 / BEE HABITAT','Interchangeable nesting cavities','Proposed cavities could provide nesting opportunities for selected solitary, cavity-nesting bee groups.'],butterfly:['04 / BUTTERFLY MODULES','Resources across life stages','Modules could combine adult nectar resources with suitable host plants for caterpillars.'],sensor:['05 / WATER + SENSORS','Environmental monitoring','Proposed sensors could monitor temperature, humidity, light and soil moisture; no live data are connected in this prototype.'],frame:['06 / MODULAR FRAME','Remove and replace components','A clamp-mounted frame is proposed to allow individual modules to be removed or replaced without replacing the full unit.']};

function initMap(){
  if(!window.L) return;
  const map=L.map('mainMap',{scrollWheelZoom:false}).setView([1.3521,103.8198],11.5);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);
  const groups={mrt:L.layerGroup().addTo(map),green:L.layerGroup().addTo(map),corridor:L.layerGroup(),frames:L.layerGroup().addTo(map),observations:L.layerGroup(),issues:L.layerGroup()};
  // These general reference features are clearly labelled as existing areas; verify operational planning with cited agencies.
  // Existing feature points are fetched from OneMap at runtime. No green-space, MRT or corridor
  // coordinates are manually embedded in this prototype.
  async function addOneMapFeature(name, group) {
    try {
      const url=`https://www.onemap.gov.sg/api/common/elastic/search?searchVal=${encodeURIComponent(name)}&returnGeom=Y&getAddrDetails=Y&pageNum=1`;
      const result=await fetch(url).then(r=>r.json()); const item=result.results?.[0];
      if (!item) return;
      const marker=L.circleMarker([Number(item.LATITUDE),Number(item.LONGITUDE)],{radius:10,color:'#477f47',fillColor:'#5f984f',fillOpacity:.7});
      marker.bindPopup(`<b>Existing reference feature</b><br>${item.SEARCHVAL || name}<br><small>Location returned by OneMap search.</small>`).addTo(group);
    } catch (_) { /* The basemap remains available if the optional public API is unavailable. */ }
  }
  addOneMapFeature('Jurong Lake Gardens',groups.green); addOneMapFeature('Tengah Forest Corridor',groups.green);
  // Official MRT and Nature Way geometry is not assumed from a hand-drawn line. It can be added
  // from an authorised OneMap/LTA/NParks dataset when available to the implementation team.
  function icon(){return L.divIcon({className:'',html:'<div style="color:#d97530;font-size:25px;text-shadow:0 1px 2px #fff">◆</div>',iconSize:[25,25],iconAnchor:[12,12]});}
  let candidateMarkers=[];
  function selectFrame(frame){document.getElementById('mapFrame').textContent=`EcoFrame #${frame.id.split('-')[1]}`;document.getElementById('mapLocation').textContent=frame.locationName;document.getElementById('mapHabitat').textContent=frame.nearbyHabitat;document.getElementById('detailLocation').textContent=frame.locationName;}
  // Initial candidates intentionally have no coordinates: exact pillar locations are not publicly asserted. Visitors may place one manually.
  map.on('click',e=>{const frame=ecoFrames.find(f=>f.id==='EF-003');frame.locationName=`Manual conceptual candidate (${e.latlng.lat.toFixed(5)}, ${e.latlng.lng.toFixed(5)})`;frame.nearbyHabitat='To be assessed';selectFrame(frame);candidateMarkers.forEach(m=>groups.frames.removeLayer(m));candidateMarkers=[];const marker=L.marker(e.latlng,{icon:icon()}).addTo(groups.frames).bindPopup('<b>PROPOSED — NOT YET INSTALLED</b><br>Manual conceptual candidate. Requires ecological, engineering and operational assessment.');candidateMarkers.push(marker);marker.on('click',()=>selectFrame(frame));marker.openPopup();renderFrames();});
  document.querySelectorAll('[data-layer]').forEach(check=>check.addEventListener('change',()=>check.checked?map.addLayer(groups[check.dataset.layer]):map.removeLayer(groups[check.dataset.layer])));
}
function renderFrames(){const tbody=document.getElementById('frameRows'); tbody.innerHTML=ecoFrames.map((f,i)=>`<tr data-index="${i}"><td><b>${f.id}</b></td><td>${f.locationName}</td><td><span class="status">⚪ Proposed</span></td><td>TBC</td><td>TBC</td><td>TBC</td><td>${f.maintenanceStatus}</td></tr>`).join('');tbody.querySelectorAll('tr').forEach(row=>row.addEventListener('click',()=>{const f=ecoFrames[row.dataset.index];document.getElementById('frameDetail').querySelector('h3').textContent=`${f.id} / Overview`;document.getElementById('detailLocation').textContent=f.locationName;}));}
function initUI(){
  document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>document.querySelector(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));
  const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>obs.observe(e));
  document.querySelectorAll('.hotspot').forEach(b=>b.addEventListener('click',()=>{const p=parts[b.dataset.part];document.getElementById('partInfo').innerHTML=`<span>${p[0]}</span><h3>${p[1]}</h3><p>${p[2]}</p>`;}));
  document.querySelectorAll('.role-tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.role-tabs .active').classList.remove('active');b.classList.add('active');const copy={Public:'View the project map, learn about Eco-Spine and submit observations.',Student:'View monitoring demonstrations, submit biodiversity observations and participate in VIA activities.', 'Project team':'Review observations, maintenance issues, demo monitoring and proposed modules.',Administrator:'Manage conceptual locations, EcoFrame records, task assignments and incoming reports.'};document.getElementById('roleText').textContent=copy[b.dataset.role]}));
  document.querySelectorAll('.module-options button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.module-options button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('replaceText').textContent=`${b.textContent} selected — in this proposed modular design, this cartridge could be removed and replaced while the standardised frame remains in place.`;}));
  document.getElementById('filterSites').addEventListener('click',()=>{document.getElementById('filterResult').textContent='0 verified installation sites returned. This prototype demonstrates criteria only; exact pillars, ecological suitability and engineering feasibility require assessment.'});
  document.querySelectorAll('.kpis button').forEach(b=>b.addEventListener('click',()=>document.getElementById('kpiMessage').textContent=`${b.textContent} selected as a proposed monitoring signal. Visitation alone does not prove improved ecological connectivity.`));
  document.querySelectorAll('.triage button').forEach(b=>b.addEventListener('click',()=>{document.getElementById('issueName').textContent=b.dataset.issue;document.getElementById('issueTitle').textContent=`${b.dataset.issue} issue`;document.getElementById('issueModal').classList.add('open');document.getElementById('issueModal').setAttribute('aria-hidden','false')}));
  document.querySelector('.close').addEventListener('click',()=>{document.getElementById('issueModal').classList.remove('open');document.getElementById('issueModal').setAttribute('aria-hidden','true')});
  document.getElementById('issueModal').addEventListener('click',e=>{if(e.target.id==='issueModal')document.querySelector('.close').click()});
  const grid=document.getElementById('plantGrid');grid.innerHTML=plantList.map((p,i)=>`<article class="plant-card"><b>${p[0]}</b><span>${p[1]}</span><p><b>Function:</b> ${p[2]}</p><p>Light: ${p[3]} · Water: ${p[4]}</p><p>Target: ${p[5]}</p><button data-plant="${i}">Support this plant</button></article>`).join('');grid.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{b.textContent=b.textContent==='Supported'?'Support this plant':'Supported';}));
  document.getElementById('observationWhen').value=new Date().toISOString().slice(0,16);renderObservations();
  document.getElementById('observationForm').addEventListener('submit',e=>{e.preventDefault();const records=JSON.parse(localStorage.getItem('ecospine-observations')||'[]');records.unshift({type:document.getElementById('observationType').value,place:document.getElementById('observationPlace').value,when:document.getElementById('observationWhen').value,text:document.getElementById('observationText').value});localStorage.setItem('ecospine-observations',JSON.stringify(records));document.getElementById('formMessage').textContent='Observation recorded — thank you for contributing to Eco-Spine’s biodiversity monitoring.';e.target.reset();document.getElementById('observationWhen').value=new Date().toISOString().slice(0,16);renderObservations();});
}
function renderObservations(){const r=JSON.parse(localStorage.getItem('ecospine-observations')||'[]');const n=t=>r.filter(x=>x.type===t).length;document.getElementById('beeCount').textContent=n('Bee')||'TBC / demo';document.getElementById('butterflyCount').textContent=n('Butterfly')||'TBC / demo';document.getElementById('otherCount').textContent=n('Other invertebrate')||'TBC / demo';document.getElementById('observationList').innerHTML=r.length?r.slice(0,3).map(x=>`<p>• ${x.type} — ${x.place}${x.text?' · '+x.text:''}</p>`).join(''):'No local observations submitted yet.'}
document.addEventListener('DOMContentLoaded',()=>{initMap();renderFrames();initUI()});
